name: Block Bundle code review

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup PHP, with composer and extensions
      uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
      with:
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, mysql, zip

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --no-interaction --no-progress

    - name: Check for vulnerabilities
      uses: symfonycorp/security-checker-action@v4
      
    - name: Run Easy Coding Standard
      run: vendor/bin/ecs check src

    - name: Run PHP Stan
      run: |
        composer require phpstan/phpstan
        composer require phpstan/extension-installer
        composer require phpstan/phpstan-symfony
        ./vendor/bin/phpstan analyse src --memory-limit 1G
